name: scrape

on:
  schedule:
    # Backs up database every day at 12:00 AM UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout files
        uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Build Scraper
        run: |
          yarn install
          yarn build
      - name: Run BBC Igbo Scraper
        run: yarn start
      - name: Run Igbo Radio Scraper
        run: yarn start:igbo_radio
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff-index --quiet HEAD || git commit -am "$R_TIME"
        env:
          R_TIME: '${{ steps.current-time.outputs.readableTime }}'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
